### ISSUE TITLE
Unable to find .eth name

### ISSUE THREAD

**Issue by torra-merin** [namesys-eth/ccip2-eth-client#25]
As told in the "Help" page, I searched a subdomain I own through the search bar. However, even though it exists and is visible in ENS, I get the following message "Name not Registered Or Expired Or in Grace".

Is something I should be doing to solve this?
Thanks!

**Comment by sshmatrix** [comment]
Hi there @torra-merin! Yes, we have noted this issue and it will be fixed in the next Client update from `v1.0.2` to `v1.1` early next week (likely Monday!) Sorry for the inconvenience!

**Comment by sshmatrix** [comment]
Fixed by https://github.com/namesys-eth/ccip2-eth-client/pull/27
